<?php 
/**
 * @noinspection KphpReturnTypeMismatchInspection
 * @noinspection NoTypeDeclarationInspection
 * @noinspection PhpFullyQualifiedNameUsageInspection
 * @noinspection PhpUnusedParameterInspection
 * @noinspection PhpIllegalPsrClassPathInspection
 * @noinspection DegradedSwitchInspection 
 */
namespace Database;



use ADO\src\Sigmalab\Database\Core\DBSettings;
use Sigmalab\Database\DatabaseArgumentException;
use Sigmalab\Database\Expressions\ExprEQ;
use Sigmalab\Database\Expressions\IExpression;
use Sigmalab\Database\Sql\SQLJoin;
use Sigmalab\IsKPHP;
use Sigmalab\SimpleReflection\ClassRegistry;
use Sigmalab\SimpleReflection\ICanReflection;
use Sigmalab\SimpleReflection\PhpReflection;

use \Sigmalab\SimpleReflection\IReflectedObject;
use \Sigmalab\SimpleReflection\ReflectionException;

//autogenerated
class DataNotNullable_reflection implements \Sigmalab\SimpleReflection\ICanReflection
{
	/** DataNotNullable */
	private DataNotNullable $instance;

	public const Field_dataNotNullableId = "dataNotNullableId";
	public const Field_valueA = "valueA";
	public const Field_valueB = "valueB";

	
	public function __construct(DataNotNullable $instance) 
	{
		$this->instance = $instance;
	}	
	/**
	 * @kphp-required
	 * @param string $name
	 * @return bool
	 */
	public function isPropertyExists(string $name):bool
	{
		//autogenerated map
		switch ($name) {
			case self::Field_dataNotNullableId: return true;
			case self::Field_valueA: return true;
			case self::Field_valueB: return true;
		}
		return false;
	}
	
	/**
	 * @kphp-required
	 * @return string[]
	 *
	 */
	public function getProperties() : array
	{
		return [self::Field_dataNotNullableId,
		self::Field_valueA,
		self::Field_valueB];
	}
	
	/**
	 * @kphp-required
	 * @param string $name
	 * @return \Sigmalab\SimpleReflection\TypeName
	 *
	 */
	public function getPropertyType(string $name) : \Sigmalab\SimpleReflection\TypeName
	{
		//autogenerated map
		switch ($name) {
			case self::Field_dataNotNullableId: return \Sigmalab\SimpleReflection\TypeName::$intValue;
			case self::Field_valueA: return \Sigmalab\SimpleReflection\TypeName::$stringValue;
			case self::Field_valueB: return \Sigmalab\SimpleReflection\TypeName::$stringValue;
			default:
				//throw new ReflectionException("Property '{$name}' not found in DataNotNullable"); 
		}
		return \Sigmalab\SimpleReflection\TypeName::$intValue;
	}
	

	/**
	 * @kphp-required
	 * @param string $name
	 * @param \Sigmalab\SimpleReflection\ValueMixed $value
	 */
	public function setPropertyValue(string $name, \Sigmalab\SimpleReflection\ValueMixed $value) : void
	{
		//autogenerated map
		switch ($name) {
/* int: int type:int isArray:  */
		case self::Field_dataNotNullableId:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->dataNotNullableId = $value->get_as_int();
			}

			break;
/* string: string type:string isArray:  */
		case self::Field_valueA:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->valueA = $value->get_as_string();
			}

			break;
/* string: string type:string isArray:  */
		case self::Field_valueB:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->valueB = $value->get_as_string();
			}

			break;
			default:
				//throw new ReflectionException("Property '{$name}' not found in DataNotNullable"); 
		}
	}

	/**
	 * @kphp-required
	 * @param string $name
	 * @return \Sigmalab\SimpleReflection\ValueMixed
	 */
	public function getPropertyValue(string $name) :\Sigmalab\SimpleReflection\ValueMixed
	{
		//autogenerated map
		switch ($name) {
			case self::Field_dataNotNullableId: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->dataNotNullableId );
			case self::Field_valueA: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->valueA );
			case self::Field_valueB: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->valueB );
			default:
				//throw new ReflectionException("Property '$name' not found in DataNotNullable");

				
		}
		return null;
	}
	
	/**  execute register class via reflection class instance */
	public function dynamicRegister(){
		self::registerClass();
	}
	/** @noinspection PhpFullyQualifiedNameUsageInspection */
	public static function registerClass()
	{   
		\Sigmalab\SimpleReflection\ClassRegistry::registerClass(DataNotNullable::class, function(){
			return instance_cast(new DataNotNullable, IReflectedObject::class ); 
		});
		\Sigmalab\SimpleReflection\ClassRegistry::registerReflection(self::class, function(object $instance){
			/** @noinspection PhpParamsInspection */ 
			return new DataNotNullable_reflection(instance_cast($instance, DataNotNullable::class)); 
		});
		
	}
	

	/**
	* @inheritDoc
	*/
	public function invoke_as_mixed(string $methodName, array $args) 
	{
		switch ($methodName)
		{
 //type: int 
			case 'primary_key_value':
				return $this->invoke_primary_key_value($args);
				break;
 //type: string 
			case 'table_name':
				return $this->invoke_table_name($args);
				break;
 //type: string 
			case 'table_description':
				return $this->invoke_table_description($args);
				break;
 //type: bool 
			case 'isNew':
				return $this->invoke_isNew($args);
				break;
 //type: bool 
			case 'set_dataNotNullableId':
				return $this->invoke_set_dataNotNullableId($args);
				break;
 //type: int 
			case 'get_dataNotNullableId':
				return $this->invoke_get_dataNotNullableId($args);
				break;
 //type: bool 
			case 'set_valueA':
				return $this->invoke_set_valueA($args);
				break;
 //type: string 
			case 'get_valueA':
				return $this->invoke_get_valueA($args);
				break;
 //type: bool 
			case 'set_valueB':
				return $this->invoke_set_valueB($args);
				break;
 //type: string 
			case 'get_valueB':
				return $this->invoke_get_valueB($args);
				break;
 //type: bool 
			case 'importValueByKey':
				return $this->invoke_importValueByKey($args);
				break;
 //type: bool 
			case 'setValue':
				return $this->invoke_setValue($args);
				break;
			default:
				//throw new ReflectionException("Property '$methodName' not found in DataNotNullable");

				
		}
	}
	/**
	* @inheritDoc
	*/
	public function invoke_as_object(string $methodName, array $args) :?IReflectedObject
	{
		return null;
	}

	/**
	 * @param string $methodName
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 */
	public function invoke_as_void(string $methodName, array $args) :void
	{
		switch ($methodName)
		{
			case 'getDataNotNullablePrototype':
				$this->invoke_getDataNotNullablePrototype($args);
				break;
			case 'getPrimaryKeyTag':
				$this->invoke_getPrimaryKeyTag($args);
				break;
			case 'primary_key_value':
				$this->invoke_primary_key_value($args);
				break;
			case 'set_primary_key_value':
				$this->invoke_set_primary_key_value($args);
				break;
			case 'createSelf':
				$this->invoke_createSelf($args);
				break;
			case 'table_name':
				$this->invoke_table_name($args);
				break;
			case 'table_description':
				$this->invoke_table_description($args);
				break;
			case 'getColumnDefinition':
				$this->invoke_getColumnDefinition($args);
				break;
			case 'getForeignKeys':
				$this->invoke_getForeignKeys($args);
				break;
			case 'isNew':
				$this->invoke_isNew($args);
				break;
			case 'set_dataNotNullableId':
				$this->invoke_set_dataNotNullableId($args);
				break;
			case 'get_dataNotNullableId':
				$this->invoke_get_dataNotNullableId($args);
				break;
			case 'set_valueA':
				$this->invoke_set_valueA($args);
				break;
			case 'get_valueA':
				$this->invoke_get_valueA($args);
				break;
			case 'set_valueB':
				$this->invoke_set_valueB($args);
				break;
			case 'get_valueB':
				$this->invoke_get_valueB($args);
				break;
			case 'importValue':
				$this->invoke_importValue($args);
				break;
			case 'importValueByKey':
				$this->invoke_importValueByKey($args);
				break;
			case 'setValue':
				$this->invoke_setValue($args);
				break;
			case 'getValue':
				$this->invoke_getValue($args);
				break;
			case 'tag_dataNotNullableId':
				$this->invoke_tag_dataNotNullableId($args);
				break;
			case 'tag_valueA':
				$this->invoke_tag_valueA($args);
				break;
			case 'tag_valueB':
				$this->invoke_tag_valueB($args);
				break;
			case 'prototypeMap':
				$this->invoke_prototypeMap($args);
				break;
			default:
				//throw new ReflectionException("Property '$methodName' not found in DataNotNullable");

				
		}
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_getDataNotNullablePrototype(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//return: Database\DataNotNullable
		$this->instance->getDataNotNullablePrototype($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_getPrimaryKeyTag(array $args)
	{
//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->getPrimaryKeyTag();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_primary_key_value(array $args)
	{
//return: int
		return $this->instance->primary_key_value();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_primary_key_value(array $args)
	{
//type: Parameter #0 [ <required> int $value ]
//param: int

		/** @var int $arg0  simple type int*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_int();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//return: void
		$this->instance->set_primary_key_value($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_createSelf(array $args)
	{
//return: Sigmalab\Database\Core\IDataObject
		$this->instance->createSelf();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_table_name(array $args)
	{
//return: string
		return $this->instance->table_name();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_table_description(array $args)
	{
//return: string
		return $this->instance->table_description();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_getColumnDefinition(array $args)
	{
//return: array
		return $this->instance->getColumnDefinition();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_getForeignKeys(array $args)
	{
//return: array
		return $this->instance->getForeignKeys();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_isNew(array $args)
	{
//return: bool
		return $this->instance->isNew();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_dataNotNullableId(array $args)
	{
//type: Parameter #0 [ <required> int or NULL $value ]
//param: int

		/** @var int $arg0  simple type int*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_int();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//return: bool
		return $this->instance->set_dataNotNullableId($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_dataNotNullableId(array $args)
	{
//return: int
		return $this->instance->get_dataNotNullableId();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_valueA(array $args)
	{
//type: Parameter #0 [ <required> string $value ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//return: bool
		return $this->instance->set_valueA($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_valueA(array $args)
	{
//return: string
		return $this->instance->get_valueA();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_valueB(array $args)
	{
//type: Parameter #0 [ <required> string $value ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//return: bool
		return $this->instance->set_valueB($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_valueB(array $args)
	{
//return: string
		return $this->instance->get_valueB();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_importValue(array $args)
	{
//type: Parameter #0 [ <required> string $name ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//type: Parameter #1 [ <required> $value ]
//param: mixed

		/** @var mixed $arg1  - mixed */      
		$value1 = $args[1];
		if ( $value1 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg1 = $value1->get_as_mixed();
		else throw new ReflectionException("Property '1' not found in DataNotNullable");

//return: void
		$this->instance->importValue($arg0,$arg1);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_importValueByKey(array $args)
	{
//type: Parameter #0 [ <required> int $key ]
//param: int

		/** @var int $arg0  simple type int*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_int();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//type: Parameter #1 [ <required> $value ]
//param: mixed

		/** @var mixed $arg1  - mixed */      
		$value1 = $args[1];
		if ( $value1 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg1 = $value1->get_as_mixed();
		else throw new ReflectionException("Property '1' not found in DataNotNullable");

//return: bool
		return $this->instance->importValueByKey($arg0,$arg1);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_setValue(array $args)
	{
//type: Parameter #0 [ <required> string $name ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//type: Parameter #1 [ <required> $value ]
//param: mixed

		/** @var mixed $arg1  - mixed */      
		$value1 = $args[1];
		if ( $value1 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg1 = $value1->get_as_mixed();
		else throw new ReflectionException("Property '1' not found in DataNotNullable");

//return: bool
		return $this->instance->setValue($arg0,$arg1);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_getValue(array $args)
	{
//type: Parameter #0 [ <required> string $name ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//return: 
		$this->instance->getValue($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_dataNotNullableId(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_dataNotNullableId($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_valueA(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_valueA($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_valueB(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in DataNotNullable");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_valueB($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_prototypeMap(array $args)
	{
//return: array
		return $this->instance->prototypeMap();
	}
	/**
	 * @param string $name
	 * @param string $value
	 * @throws \Exception
	 */
	public function set_as_string(string  $name, string $value):void
	{
		switch ($name) {
			case self::Field_valueA: $this->instance->valueA  = $value; break;
			case self::Field_valueB: $this->instance->valueB  = $value; break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
	}
	/**
	 * @param string $name
	 * @return string
	 * @throws \Exception
	 */
	public function get_as_string(string  $name):string
	{
		switch ($name) {
			case self::Field_valueA: return (string)$this->instance->valueA;
			case self::Field_valueB: return (string)$this->instance->valueB;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return "";
	}
	/**
	 * @param string $name
	 * @param int $value
	 * @throws \Exception
	 */
	public function set_as_int(string  $name, int $value):void
	{
		switch ($name) {
			case self::Field_dataNotNullableId: $this->instance->dataNotNullableId  = $value; break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
	}
	/**
	 * @param string $name
	 * @return int
	 * @throws \Exception
	 */
	public function get_as_int(string  $name):int
	{
		switch ($name) {
			case self::Field_dataNotNullableId: return (int)$this->instance->dataNotNullableId;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return 0;
	}
	/**
	 * @param string $name
	 * @param float $value
	 * @throws \Exception
	 */
	public function set_as_float(string  $name, float $value):void
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
	}
	/**
	 * @param string $name
	 * @return float
	 * @throws \Exception
	 */
	public function get_as_float(string  $name):float
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return 0.0;
	}
	/**
	 * @param string $name
	 * @param bool $value
	 * @throws \Exception
	 */
	public function set_as_bool(string  $name, bool $value):void
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
	}
	/**
	 * @param string $name
	 * @return bool
	 * @throws \Exception
	 */
	public function get_as_bool(string  $name):bool
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return false;
	}
	/**
	 * @param string $name
	 * @throws \Exception
	 */
	public function set_as_null(string  $name):void
	{
		switch ($name) {
			case self::Field_dataNotNullableId: $this->instance->dataNotNullableId  = null; break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
	}
	/**
	 * @param string $name
	 * @param mixed $value
	 * @throws \Exception
	 */
	public function set_as_mixed(string $name, $value):void
	{
		switch ($name) {
			case self::Field_dataNotNullableId: 
				if ( is_null($value) ) $this->instance->dataNotNullableId = null;
				else $this->instance->dataNotNullableId  = (int)$value; 
				break;
			case self::Field_valueA: $this->instance->valueA  = (string)$value; break;
			case self::Field_valueB: $this->instance->valueB  = (string)$value; break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
	}
	/**
	 * @param string $name
	 * @return mixed
	 * @throws \Exception
	 */
	public function get_as_mixed(string $name)
	{
		switch ($name) {
			case self::Field_dataNotNullableId: return $this->instance->dataNotNullableId; break;
			case self::Field_valueA: return $this->instance->valueA; break;
			case self::Field_valueB: return $this->instance->valueB; break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return 0;
	}
	/**
	 * @param string $name
	 * @param \Sigmalab\SimpleReflection\IReflectedObject $value
	 * @throws \Exception
	 */
	public function set_as_object(string $name, \Sigmalab\SimpleReflection\IReflectedObject $value):void
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
	}

	/**
	 * @param string $name
	 * @return \Sigmalab\SimpleReflection\IReflectedObject|null 
	 * @throws \Exception
	 */
	public function get_as_object(string $name):?\Sigmalab\SimpleReflection\IReflectedObject 
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return null;
	}

	/**
	 * @param string $name
	 * @param \Sigmalab\SimpleReflection\IReflectedObject[] $value
	 * @throws \Exception
	 */
	public function set_as_objects(string $name, array $value):void
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
	}

	/**
	 * @param string $name
	 * @return \Sigmalab\SimpleReflection\IReflectedObject[] 
	 * @throws \Exception
	 */
	public function get_as_objects(string $name):array
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\DataNotNullable");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return [];
	}
}
