<?php 
/**
 * @noinspection KphpReturnTypeMismatchInspection
 * @noinspection NoTypeDeclarationInspection
 * @noinspection PhpFullyQualifiedNameUsageInspection
 * @noinspection PhpUnusedParameterInspection
 * @noinspection PhpIllegalPsrClassPathInspection
 * @noinspection DegradedSwitchInspection 
 */
namespace Database;



use ADO\src\Sigmalab\Database\Core\DBSettings;
use Sigmalab\Database\DatabaseArgumentException;
use Sigmalab\Database\Expressions\ExprEQ;
use Sigmalab\Database\Expressions\IExpression;
use Sigmalab\Database\Sql\SQLJoin;
use Sigmalab\IsKPHP;
use Sigmalab\SimpleReflection\ClassRegistry;
use Sigmalab\SimpleReflection\ICanReflection;
use Sigmalab\SimpleReflection\PhpReflection;

use \Sigmalab\SimpleReflection\IReflectedObject;
use \Sigmalab\SimpleReflection\ReflectionException;

//autogenerated
class Data_reflection implements \Sigmalab\SimpleReflection\ICanReflection
{
	/** Data */
	private Data $instance;

	public const Field_data_id = "data_id";
	public const Field_date = "date";
	public const Field_value = "value";
	public const Field_string = "string";
	public const Field_text = "text";
	public const Field_blob = "blob";
	public const Field_real = "real";
	public const Field_dictionary_id = "dictionary_id";

	
	public function __construct(Data $instance) 
	{
		$this->instance = $instance;
	}	
	/**
	 * @kphp-required
	 * @param string $name
	 * @return bool
	 */
	public function isPropertyExists(string $name):bool
	{
		//autogenerated map
		switch ($name) {
			case self::Field_data_id: return true;
			case self::Field_date: return true;
			case self::Field_value: return true;
			case self::Field_string: return true;
			case self::Field_text: return true;
			case self::Field_blob: return true;
			case self::Field_real: return true;
			case self::Field_dictionary_id: return true;
		}
		return false;
	}
	
	/**
	 * @kphp-required
	 * @return string[]
	 *
	 */
	public function getProperties() : array
	{
		return [self::Field_data_id,
		self::Field_date,
		self::Field_value,
		self::Field_string,
		self::Field_text,
		self::Field_blob,
		self::Field_real,
		self::Field_dictionary_id];
	}
	
	/**
	 * @kphp-required
	 * @param string $name
	 * @return \Sigmalab\SimpleReflection\TypeName
	 *
	 */
	public function getPropertyType(string $name) : \Sigmalab\SimpleReflection\TypeName
	{
		//autogenerated map
		switch ($name) {
			case self::Field_data_id: return \Sigmalab\SimpleReflection\TypeName::$intValue;
			case self::Field_date: return \Sigmalab\SimpleReflection\TypeName::$intValue;
			case self::Field_value: return \Sigmalab\SimpleReflection\TypeName::$intValue;
			case self::Field_string: return \Sigmalab\SimpleReflection\TypeName::$stringValue;
			case self::Field_text: return \Sigmalab\SimpleReflection\TypeName::$stringValue;
			case self::Field_blob: return \Sigmalab\SimpleReflection\TypeName::$stringValue;
			case self::Field_real: return \Sigmalab\SimpleReflection\TypeName::$floatValue;
			case self::Field_dictionary_id: return \Sigmalab\SimpleReflection\TypeName::$intValue;
			default:
				//throw new ReflectionException("Property '{$name}' not found in Data"); 
		}
		return \Sigmalab\SimpleReflection\TypeName::$intValue;
	}
	

	/**
	 * @kphp-required
	 * @param string $name
	 * @param \Sigmalab\SimpleReflection\ValueMixed $value
	 */
	public function setPropertyValue(string $name, \Sigmalab\SimpleReflection\ValueMixed $value) : void
	{
		//autogenerated map
		switch ($name) {
/* int: int type:int isArray:  */
		case self::Field_data_id:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->data_id = $value->get_as_int();
			}

			break;
/* int: int type:NULL isArray:  */
		case self::Field_date:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->date = $value->get_as_int();
			}

			break;
/* int: int type:NULL isArray:  */
		case self::Field_value:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->value = $value->get_as_int();
			}

			break;
/* string: string type:NULL isArray:  */
		case self::Field_string:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->string = $value->get_as_string();
			}

			break;
/* string: string type:NULL isArray:  */
		case self::Field_text:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->text = $value->get_as_string();
			}

			break;
/* string: string type:NULL isArray:  */
		case self::Field_blob:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->blob = $value->get_as_string();
			}

			break;
/* float: float type:NULL isArray:  */
		case self::Field_real:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->real = $value->get_as_float();
			}

			break;
/* int: int type:NULL isArray:  */
		case self::Field_dictionary_id:
			if ($value instanceof \Sigmalab\SimpleReflection\ValueScalar) {
				$this->instance->dictionary_id = $value->get_as_int();
			}

			break;
			default:
				//throw new ReflectionException("Property '{$name}' not found in Data"); 
		}
	}

	/**
	 * @kphp-required
	 * @param string $name
	 * @return \Sigmalab\SimpleReflection\ValueMixed
	 */
	public function getPropertyValue(string $name) :\Sigmalab\SimpleReflection\ValueMixed
	{
		//autogenerated map
		switch ($name) {
			case self::Field_data_id: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->data_id );
			case self::Field_date: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->date );
			case self::Field_value: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->value );
			case self::Field_string: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->string );
			case self::Field_text: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->text );
			case self::Field_blob: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->blob );
			case self::Field_real: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->real );
			case self::Field_dictionary_id: return new \Sigmalab\SimpleReflection\ValueScalar( $this->instance->dictionary_id );
			default:
				//throw new ReflectionException("Property '$name' not found in Data");

				
		}
		return null;
	}
	
	/**  execute register class via reflection class instance */
	public function dynamicRegister(){
		self::registerClass();
	}
	/** @noinspection PhpFullyQualifiedNameUsageInspection */
	public static function registerClass()
	{   
		\Sigmalab\SimpleReflection\ClassRegistry::registerClass(Data::class, function(){
			return instance_cast(new Data, IReflectedObject::class ); 
		});
		\Sigmalab\SimpleReflection\ClassRegistry::registerReflection(self::class, function(object $instance){
			/** @noinspection PhpParamsInspection */ 
			return new Data_reflection(instance_cast($instance, Data::class)); 
		});
		
	}
	

	/**
	* @inheritDoc
	*/
	public function invoke_as_mixed(string $methodName, array $args) 
	{
		switch ($methodName)
		{
 //type: int 
			case 'primary_key_value':
				return $this->invoke_primary_key_value($args);
				break;
 //type: string 
			case 'table_name':
				return $this->invoke_table_name($args);
				break;
 //type: string 
			case 'table_description':
				return $this->invoke_table_description($args);
				break;
 //type: bool 
			case 'isNew':
				return $this->invoke_isNew($args);
				break;
 //type: bool 
			case 'set_data_id':
				return $this->invoke_set_data_id($args);
				break;
 //type: int 
			case 'get_data_id':
				return $this->invoke_get_data_id($args);
				break;
 //type: bool 
			case 'set_date':
				return $this->invoke_set_date($args);
				break;
 //type: int 
			case 'get_date':
				return $this->invoke_get_date($args);
				break;
 //type: bool 
			case 'set_value':
				return $this->invoke_set_value($args);
				break;
 //type: int 
			case 'get_value':
				return $this->invoke_get_value($args);
				break;
 //type: bool 
			case 'set_string':
				return $this->invoke_set_string($args);
				break;
 //type: string 
			case 'get_string':
				return $this->invoke_get_string($args);
				break;
 //type: bool 
			case 'set_text':
				return $this->invoke_set_text($args);
				break;
 //type: string 
			case 'get_text':
				return $this->invoke_get_text($args);
				break;
 //type: bool 
			case 'set_blob':
				return $this->invoke_set_blob($args);
				break;
 //type: string 
			case 'get_blob':
				return $this->invoke_get_blob($args);
				break;
 //type: bool 
			case 'set_real':
				return $this->invoke_set_real($args);
				break;
 //type: float 
			case 'get_real':
				return $this->invoke_get_real($args);
				break;
 //type: bool 
			case 'set_dictionary_id':
				return $this->invoke_set_dictionary_id($args);
				break;
 //type: int 
			case 'get_dictionary_id':
				return $this->invoke_get_dictionary_id($args);
				break;
 //type: bool 
			case 'importValueByKey':
				return $this->invoke_importValueByKey($args);
				break;
 //type: bool 
			case 'setValue':
				return $this->invoke_setValue($args);
				break;
			default:
				//throw new ReflectionException("Property '$methodName' not found in Data");

				
		}
	}
	/**
	* @inheritDoc
	*/
	public function invoke_as_object(string $methodName, array $args) :?IReflectedObject
	{
		return null;
	}

	/**
	 * @param string $methodName
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 */
	public function invoke_as_void(string $methodName, array $args) :void
	{
		switch ($methodName)
		{
			case 'getDataPrototype':
				$this->invoke_getDataPrototype($args);
				break;
			case 'getPrimaryKeyTag':
				$this->invoke_getPrimaryKeyTag($args);
				break;
			case 'primary_key_value':
				$this->invoke_primary_key_value($args);
				break;
			case 'set_primary_key_value':
				$this->invoke_set_primary_key_value($args);
				break;
			case 'createSelf':
				$this->invoke_createSelf($args);
				break;
			case 'table_name':
				$this->invoke_table_name($args);
				break;
			case 'table_description':
				$this->invoke_table_description($args);
				break;
			case 'getColumnDefinition':
				$this->invoke_getColumnDefinition($args);
				break;
			case 'getForeignKeys':
				$this->invoke_getForeignKeys($args);
				break;
			case 'isNew':
				$this->invoke_isNew($args);
				break;
			case 'set_data_id':
				$this->invoke_set_data_id($args);
				break;
			case 'get_data_id':
				$this->invoke_get_data_id($args);
				break;
			case 'set_date':
				$this->invoke_set_date($args);
				break;
			case 'get_date':
				$this->invoke_get_date($args);
				break;
			case 'set_value':
				$this->invoke_set_value($args);
				break;
			case 'get_value':
				$this->invoke_get_value($args);
				break;
			case 'set_string':
				$this->invoke_set_string($args);
				break;
			case 'get_string':
				$this->invoke_get_string($args);
				break;
			case 'set_text':
				$this->invoke_set_text($args);
				break;
			case 'get_text':
				$this->invoke_get_text($args);
				break;
			case 'set_blob':
				$this->invoke_set_blob($args);
				break;
			case 'get_blob':
				$this->invoke_get_blob($args);
				break;
			case 'set_real':
				$this->invoke_set_real($args);
				break;
			case 'get_real':
				$this->invoke_get_real($args);
				break;
			case 'set_dictionary_id':
				$this->invoke_set_dictionary_id($args);
				break;
			case 'get_dictionary_id':
				$this->invoke_get_dictionary_id($args);
				break;
			case 'importValue':
				$this->invoke_importValue($args);
				break;
			case 'importValueByKey':
				$this->invoke_importValueByKey($args);
				break;
			case 'setValue':
				$this->invoke_setValue($args);
				break;
			case 'getValue':
				$this->invoke_getValue($args);
				break;
			case 'tag_data_id':
				$this->invoke_tag_data_id($args);
				break;
			case 'tag_date':
				$this->invoke_tag_date($args);
				break;
			case 'tag_value':
				$this->invoke_tag_value($args);
				break;
			case 'tag_string':
				$this->invoke_tag_string($args);
				break;
			case 'tag_text':
				$this->invoke_tag_text($args);
				break;
			case 'tag_blob':
				$this->invoke_tag_blob($args);
				break;
			case 'tag_real':
				$this->invoke_tag_real($args);
				break;
			case 'tag_dictionary_id':
				$this->invoke_tag_dictionary_id($args);
				break;
			case 'prototypeMap':
				$this->invoke_prototypeMap($args);
				break;
			case 'key_dictionary_id':
				$this->invoke_key_dictionary_id($args);
				break;
			default:
				//throw new ReflectionException("Property '$methodName' not found in Data");

				
		}
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_getDataPrototype(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: Database\Data
		$this->instance->getDataPrototype($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_getPrimaryKeyTag(array $args)
	{
//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->getPrimaryKeyTag();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_primary_key_value(array $args)
	{
//return: int
		return $this->instance->primary_key_value();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_primary_key_value(array $args)
	{
//type: Parameter #0 [ <required> int $value ]
//param: int

		/** @var int $arg0  simple type int*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_int();
		else throw new ReflectionException("Property '0' not found in Data");

//return: void
		$this->instance->set_primary_key_value($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_createSelf(array $args)
	{
//return: Sigmalab\Database\Core\IDataObject
		$this->instance->createSelf();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_table_name(array $args)
	{
//return: string
		return $this->instance->table_name();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_table_description(array $args)
	{
//return: string
		return $this->instance->table_description();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_getColumnDefinition(array $args)
	{
//return: array
		return $this->instance->getColumnDefinition();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_getForeignKeys(array $args)
	{
//return: array
		return $this->instance->getForeignKeys();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_isNew(array $args)
	{
//return: bool
		return $this->instance->isNew();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_data_id(array $args)
	{
//type: Parameter #0 [ <required> int or NULL $value ]
//param: int

		/** @var int $arg0  simple type int*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_int();
		else throw new ReflectionException("Property '0' not found in Data");

//return: bool
		return $this->instance->set_data_id($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_data_id(array $args)
	{
//return: int
		return $this->instance->get_data_id();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_date(array $args)
	{
//type: Parameter #0 [ <required> int or NULL $value ]
//param: int

		/** @var int $arg0  simple type int*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_int();
		else throw new ReflectionException("Property '0' not found in Data");

//return: bool
		return $this->instance->set_date($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_date(array $args)
	{
//return: int
		return $this->instance->get_date();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_value(array $args)
	{
//type: Parameter #0 [ <required> int or NULL $value ]
//param: int

		/** @var int $arg0  simple type int*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_int();
		else throw new ReflectionException("Property '0' not found in Data");

//return: bool
		return $this->instance->set_value($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_value(array $args)
	{
//return: int
		return $this->instance->get_value();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_string(array $args)
	{
//type: Parameter #0 [ <required> string or NULL $value ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: bool
		return $this->instance->set_string($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_string(array $args)
	{
//return: string
		return $this->instance->get_string();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_text(array $args)
	{
//type: Parameter #0 [ <required> string or NULL $value ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: bool
		return $this->instance->set_text($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_text(array $args)
	{
//return: string
		return $this->instance->get_text();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_blob(array $args)
	{
//type: Parameter #0 [ <required> string or NULL $value ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: bool
		return $this->instance->set_blob($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_blob(array $args)
	{
//return: string
		return $this->instance->get_blob();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_real(array $args)
	{
//type: Parameter #0 [ <required> float or NULL $value ]
//param: float

		/** @var float $arg0  simple type float*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_float();
		else throw new ReflectionException("Property '0' not found in Data");

//return: bool
		return $this->instance->set_real($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_real(array $args)
	{
//return: float
		return $this->instance->get_real();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_set_dictionary_id(array $args)
	{
//type: Parameter #0 [ <required> int or NULL $value ]
//param: int

		/** @var int $arg0  simple type int*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_int();
		else throw new ReflectionException("Property '0' not found in Data");

//return: bool
		return $this->instance->set_dictionary_id($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_get_dictionary_id(array $args)
	{
//return: int
		return $this->instance->get_dictionary_id();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_importValue(array $args)
	{
//type: Parameter #0 [ <required> string $name ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//type: Parameter #1 [ <required> $value ]
//param: mixed

		/** @var mixed $arg1  - mixed */      
		$value1 = $args[1];
		if ( $value1 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg1 = $value1->get_as_mixed();
		else throw new ReflectionException("Property '1' not found in Data");

//return: void
		$this->instance->importValue($arg0,$arg1);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_importValueByKey(array $args)
	{
//type: Parameter #0 [ <required> int $key ]
//param: int

		/** @var int $arg0  simple type int*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_int();
		else throw new ReflectionException("Property '0' not found in Data");

//type: Parameter #1 [ <required> $value ]
//param: mixed

		/** @var mixed $arg1  - mixed */      
		$value1 = $args[1];
		if ( $value1 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg1 = $value1->get_as_mixed();
		else throw new ReflectionException("Property '1' not found in Data");

//return: bool
		return $this->instance->importValueByKey($arg0,$arg1);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_setValue(array $args)
	{
//type: Parameter #0 [ <required> string $name ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//type: Parameter #1 [ <required> $value ]
//param: mixed

		/** @var mixed $arg1  - mixed */      
		$value1 = $args[1];
		if ( $value1 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg1 = $value1->get_as_mixed();
		else throw new ReflectionException("Property '1' not found in Data");

//return: bool
		return $this->instance->setValue($arg0,$arg1);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_getValue(array $args)
	{
//type: Parameter #0 [ <required> string $name ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: 
		$this->instance->getValue($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_data_id(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_data_id($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_date(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_date($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_value(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_value($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_string(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_string($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_text(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_text($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_blob(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_blob($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_real(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_real($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_tag_dictionary_id(array $args)
	{
//type: Parameter #0 [ <optional> string or NULL $alias = NULL ]
//param: string

		/** @var string $arg0  simple type string*/      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueScalar) $arg0 = $value0->get_as_string();
		else throw new ReflectionException("Property '0' not found in Data");

//return: Sigmalab\Database\Core\IDBColumnDefinition
		$this->instance->tag_dictionary_id($arg0);
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_prototypeMap(array $args)
	{
//return: array
		return $this->instance->prototypeMap();
	}

	/**
	 * @param \Sigmalab\SimpleReflection\ValueMixed[] $args
	 * @throws \Exception
	 * 
	 */
	private function invoke_key_dictionary_id(array $args)
	{
//type: Parameter #0 [ <optional> Database\Dictionary or NULL $proto = NULL ]
//param: \Database\Dictionary

		/** @var \Database\Dictionary $arg0 - object  */      
		$value0 = $args[0];
		if ( $value0 instanceof \Sigmalab\SimpleReflection\ValueObject) $arg0 = instance_cast($value0, \Database\Dictionary::class);
		else throw new ReflectionException("Property '0' not found in Data");

//return: Sigmalab\Database\Core\DBForeignKey
		$this->instance->key_dictionary_id($arg0);
	}
	/**
	 * @param string $name
	 * @param string $value
	 * @throws \Exception
	 */
	public function set_as_string(string  $name, string $value):void
	{
		switch ($name) {
			case self::Field_string: $this->instance->string  = $value; break;
			case self::Field_text: $this->instance->text  = $value; break;
			case self::Field_blob: $this->instance->blob  = $value; break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
	}
	/**
	 * @param string $name
	 * @return string
	 * @throws \Exception
	 */
	public function get_as_string(string  $name):string
	{
		switch ($name) {
			case self::Field_string: return (string)$this->instance->string;
			case self::Field_text: return (string)$this->instance->text;
			case self::Field_blob: return (string)$this->instance->blob;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return "";
	}
	/**
	 * @param string $name
	 * @param int $value
	 * @throws \Exception
	 */
	public function set_as_int(string  $name, int $value):void
	{
		switch ($name) {
			case self::Field_data_id: $this->instance->data_id  = $value; break;
			case self::Field_date: $this->instance->date  = $value; break;
			case self::Field_value: $this->instance->value  = $value; break;
			case self::Field_dictionary_id: $this->instance->dictionary_id  = $value; break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
	}
	/**
	 * @param string $name
	 * @return int
	 * @throws \Exception
	 */
	public function get_as_int(string  $name):int
	{
		switch ($name) {
			case self::Field_data_id: return (int)$this->instance->data_id;
			case self::Field_date: return (int)$this->instance->date;
			case self::Field_value: return (int)$this->instance->value;
			case self::Field_dictionary_id: return (int)$this->instance->dictionary_id;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return 0;
	}
	/**
	 * @param string $name
	 * @param float $value
	 * @throws \Exception
	 */
	public function set_as_float(string  $name, float $value):void
	{
		switch ($name) {
			case self::Field_real: $this->instance->real  = $value; break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
	}
	/**
	 * @param string $name
	 * @return float
	 * @throws \Exception
	 */
	public function get_as_float(string  $name):float
	{
		switch ($name) {
			case self::Field_real: return (float)$this->instance->real;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return 0.0;
	}
	/**
	 * @param string $name
	 * @param bool $value
	 * @throws \Exception
	 */
	public function set_as_bool(string  $name, bool $value):void
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
	}
	/**
	 * @param string $name
	 * @return bool
	 * @throws \Exception
	 */
	public function get_as_bool(string  $name):bool
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return false;
	}
	/**
	 * @param string $name
	 * @throws \Exception
	 */
	public function set_as_null(string  $name):void
	{
		switch ($name) {
			case self::Field_data_id: $this->instance->data_id  = null; break;
			case self::Field_date: $this->instance->date  = null; break;
			case self::Field_value: $this->instance->value  = null; break;
			case self::Field_string: $this->instance->string  = null; break;
			case self::Field_text: $this->instance->text  = null; break;
			case self::Field_blob: $this->instance->blob  = null; break;
			case self::Field_real: $this->instance->real  = null; break;
			case self::Field_dictionary_id: $this->instance->dictionary_id  = null; break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
	}
	/**
	 * @param string $name
	 * @param mixed $value
	 * @throws \Exception
	 */
	public function set_as_mixed(string $name, $value):void
	{
		switch ($name) {
			case self::Field_data_id: 
				if ( is_null($value) ) $this->instance->data_id = null;
				else $this->instance->data_id  = (int)$value; 
				break;
			case self::Field_date: 
				if ( is_null($value) ) $this->instance->date = null;
				else $this->instance->date  = (int)$value; 
				break;
			case self::Field_value: 
				if ( is_null($value) ) $this->instance->value = null;
				else $this->instance->value  = (int)$value; 
				break;
			case self::Field_string: 
				if ( is_null($value) ) $this->instance->string = null;
				else $this->instance->string  = (string)$value; 
				break;
			case self::Field_text: 
				if ( is_null($value) ) $this->instance->text = null;
				else $this->instance->text  = (string)$value; 
				break;
			case self::Field_blob: 
				if ( is_null($value) ) $this->instance->blob = null;
				else $this->instance->blob  = (string)$value; 
				break;
			case self::Field_real: 
				if ( is_null($value) ) $this->instance->real = null;
				else $this->instance->real  = (float)$value; 
				break;
			case self::Field_dictionary_id: 
				if ( is_null($value) ) $this->instance->dictionary_id = null;
				else $this->instance->dictionary_id  = (int)$value; 
				break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
	}
	/**
	 * @param string $name
	 * @return mixed
	 * @throws \Exception
	 */
	public function get_as_mixed(string $name)
	{
		switch ($name) {
			case self::Field_data_id: return $this->instance->data_id; break;
			case self::Field_date: return $this->instance->date; break;
			case self::Field_value: return $this->instance->value; break;
			case self::Field_string: return $this->instance->string; break;
			case self::Field_text: return $this->instance->text; break;
			case self::Field_blob: return $this->instance->blob; break;
			case self::Field_real: return $this->instance->real; break;
			case self::Field_dictionary_id: return $this->instance->dictionary_id; break;
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return 0;
	}
	/**
	 * @param string $name
	 * @param \Sigmalab\SimpleReflection\IReflectedObject $value
	 * @throws \Exception
	 */
	public function set_as_object(string $name, \Sigmalab\SimpleReflection\IReflectedObject $value):void
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
	}

	/**
	 * @param string $name
	 * @return \Sigmalab\SimpleReflection\IReflectedObject|null 
	 * @throws \Exception
	 */
	public function get_as_object(string $name):?\Sigmalab\SimpleReflection\IReflectedObject 
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return null;
	}

	/**
	 * @param string $name
	 * @param \Sigmalab\SimpleReflection\IReflectedObject[] $value
	 * @throws \Exception
	 */
	public function set_as_objects(string $name, array $value):void
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
	}

	/**
	 * @param string $name
	 * @return \Sigmalab\SimpleReflection\IReflectedObject[] 
	 * @throws \Exception
	 */
	public function get_as_objects(string $name):array
	{
		switch ($name) {
			default: 
			//throw new ReflectionException("Property '$name' not found in \Database\Data");
		}
		/** @noinspection PhpUnreachableStatementInspection */
		return [];
	}
}
